/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package com.epicsoft.expensemanager.view;

import com.epicsoft.expensemanager.controller.AccountController;
import com.epicsoft.expensemanager.model.Account;
import java.awt.Color;
import java.sql.SQLException;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JLabel;
import javax.swing.JPanel;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author hp
 */
public class MainWindow extends javax.swing.JFrame {

    private JLabel buttonList[];
    private JPanel panelList[];
    private String activeUser;
    
    private DefaultTableModel accountDTM;
    /**
     * Creates new form MainWindow
     */
    public MainWindow() {
        initComponents();
        buttonList = new JLabel[] {overviewButton, accountsButton, accountActivitiesButton, expensesButton, earningsButton, budgetButton, manageCategoriesButton, reportsButton, configurationButton, aboutButton, helpButton};
        panelList = new JPanel[] {overviewPanel, accountsPanel, accountActivitiesPanel, expensesPanel, earningsPanel, budgetPanel, manageCategoriesPanel, reportPanel, configurationPanel, aboutPanel, helpPanel};
        this.getContentPane().setBackground(Color.WHITE);
        accountDTM = (DefaultTableModel) accountTable.getModel();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        AccActivityTimePeriod = new javax.swing.ButtonGroup();
        ExpenseTimePeriod = new javax.swing.ButtonGroup();
        EarningsTimePeriod = new javax.swing.ButtonGroup();
        activeUserLabel = new javax.swing.JLabel();
        changeUserButton = new javax.swing.JLabel();
        tabItemsPanel = new javax.swing.JPanel();
        overviewButton = new javax.swing.JLabel();
        accountsButton = new javax.swing.JLabel();
        accountActivitiesButton = new javax.swing.JLabel();
        expensesButton = new javax.swing.JLabel();
        earningsButton = new javax.swing.JLabel();
        budgetButton = new javax.swing.JLabel();
        manageCategoriesButton = new javax.swing.JLabel();
        reportsButton = new javax.swing.JLabel();
        configurationButton = new javax.swing.JLabel();
        aboutButton = new javax.swing.JLabel();
        helpButton = new javax.swing.JLabel();
        jLayeredPane1 = new javax.swing.JLayeredPane();
        overviewPanel = new javax.swing.JPanel();
        defaultAccLabel = new javax.swing.JLabel();
        defaultAccBalanceLabel = new javax.swing.JLabel();
        defAccIncome = new javax.swing.JLabel();
        defAccIncomeLabel = new javax.swing.JLabel();
        defAccExpense = new javax.swing.JLabel();
        defAccExpenseLabel = new javax.swing.JLabel();
        secondAccountLabel = new javax.swing.JLabel();
        secondAccountBalance = new javax.swing.JLabel();
        secAccIncomeLabel = new javax.swing.JLabel();
        secAccExpenseLabel = new javax.swing.JLabel();
        secAccExpense = new javax.swing.JLabel();
        secAccIncome = new javax.swing.JLabel();
        accSummaryBox = new javax.swing.JLabel();
        addExpenseButton = new javax.swing.JLabel();
        addEarningButton = new javax.swing.JLabel();
        accountsPanel = new javax.swing.JPanel();
        addNewAccountButton = new javax.swing.JLabel();
        editAccountButton = new javax.swing.JLabel();
        deleteAccountButton = new javax.swing.JLabel();
        viewActivitiesButton = new javax.swing.JLabel();
        transferButton = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        accountTable = new javax.swing.JTable();
        accountActivitiesPanel = new javax.swing.JPanel();
        accountLabel = new javax.swing.JLabel();
        accountComboBox = new javax.swing.JComboBox();
        allTimeRadioButton = new javax.swing.JRadioButton();
        yearlyRadioButton = new javax.swing.JRadioButton();
        monthlyRadioButton = new javax.swing.JRadioButton();
        dailyRadioButton = new javax.swing.JRadioButton();
        deleteButton = new javax.swing.JLabel();
        editButton = new javax.swing.JLabel();
        addNewButton = new javax.swing.JLabel();
        expensesPanel = new javax.swing.JPanel();
        expenseCategoryComboBox = new javax.swing.JComboBox();
        CategoryLabel = new javax.swing.JLabel();
        addNewButton1 = new javax.swing.JLabel();
        editButton1 = new javax.swing.JLabel();
        deleteButton1 = new javax.swing.JLabel();
        allTimeRadioButton1 = new javax.swing.JRadioButton();
        yearlyRadioButton1 = new javax.swing.JRadioButton();
        monthlyRadioButton1 = new javax.swing.JRadioButton();
        dailyRadioButton1 = new javax.swing.JRadioButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        earningsPanel = new javax.swing.JPanel();
        earningCategoryComboBox = new javax.swing.JComboBox();
        accountLabel2 = new javax.swing.JLabel();
        addNewButton2 = new javax.swing.JLabel();
        editButton2 = new javax.swing.JLabel();
        deleteButton2 = new javax.swing.JLabel();
        yearlyRadioButton2 = new javax.swing.JRadioButton();
        allTimeRadioButton2 = new javax.swing.JRadioButton();
        monthlyRadioButton2 = new javax.swing.JRadioButton();
        dailyRadioButton2 = new javax.swing.JRadioButton();
        budgetPanel = new javax.swing.JPanel();
        manageCategoriesPanel = new javax.swing.JPanel();
        addCategoryButton = new javax.swing.JLabel();
        editCateogryButton = new javax.swing.JLabel();
        deleteCategoryButton = new javax.swing.JLabel();
        reportPanel = new javax.swing.JPanel();
        configurationPanel = new javax.swing.JPanel();
        aboutPanel = new javax.swing.JPanel();
        helpPanel = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Expense Manager");
        setBackground(new java.awt.Color(255, 255, 255));
        setForeground(java.awt.Color.white);
        setIconImages(null);

        activeUserLabel.setBackground(new java.awt.Color(255, 153, 255));
        activeUserLabel.setFont(new java.awt.Font("Segoe UI Semibold", 0, 14)); // NOI18N
        activeUserLabel.setForeground(new java.awt.Color(255, 102, 255));
        activeUserLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);

        changeUserButton.setFont(new java.awt.Font("Segoe UI Semibold", 0, 12)); // NOI18N
        changeUserButton.setForeground(new java.awt.Color(255, 102, 255));
        changeUserButton.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        changeUserButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/epicsoft/expensemanager/guiImages/UserButtonBackground.png"))); // NOI18N
        changeUserButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                changeUserButtonMouseClicked(evt);
            }
        });

        tabItemsPanel.setPreferredSize(new java.awt.Dimension(150, 669));

        overviewButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/epicsoft/expensemanager/guiImages/OverviewActive.png"))); // NOI18N
        overviewButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                overviewButtonMouseClicked(evt);
            }
        });

        accountsButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/epicsoft/expensemanager/guiImages/AccountsInactive.png"))); // NOI18N
        accountsButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                accountsButtonMouseClicked(evt);
            }
        });

        accountActivitiesButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/epicsoft/expensemanager/guiImages/AccountActivitiesInactive.png"))); // NOI18N
        accountActivitiesButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                accountActivitiesButtonMouseClicked(evt);
            }
        });

        expensesButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/epicsoft/expensemanager/guiImages/ExpensesInactive.png"))); // NOI18N
        expensesButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                expensesButtonMouseClicked(evt);
            }
        });

        earningsButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/epicsoft/expensemanager/guiImages/EarningsInactive.png"))); // NOI18N
        earningsButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                earningsButtonMouseClicked(evt);
            }
        });

        budgetButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/epicsoft/expensemanager/guiImages/BudgetInactive.png"))); // NOI18N
        budgetButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                budgetButtonMouseClicked(evt);
            }
        });

        manageCategoriesButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/epicsoft/expensemanager/guiImages/ManageCategoriesInactive.png"))); // NOI18N
        manageCategoriesButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                manageCategoriesButtonMouseClicked(evt);
            }
        });

        reportsButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/epicsoft/expensemanager/guiImages/ReportsInactive.png"))); // NOI18N
        reportsButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                reportsButtonMouseClicked(evt);
            }
        });

        configurationButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/epicsoft/expensemanager/guiImages/ConfigurationInactive.png"))); // NOI18N
        configurationButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                configurationButtonMouseClicked(evt);
            }
        });

        aboutButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/epicsoft/expensemanager/guiImages/AboutInactive.png"))); // NOI18N
        aboutButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                aboutButtonMouseClicked(evt);
            }
        });

        helpButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/epicsoft/expensemanager/guiImages/HelpInactive.png"))); // NOI18N
        helpButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                helpButtonMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout tabItemsPanelLayout = new javax.swing.GroupLayout(tabItemsPanel);
        tabItemsPanel.setLayout(tabItemsPanelLayout);
        tabItemsPanelLayout.setHorizontalGroup(
            tabItemsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(overviewButton, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addComponent(accountsButton, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addComponent(accountActivitiesButton, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addComponent(expensesButton, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addComponent(earningsButton, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addComponent(budgetButton, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addComponent(reportsButton, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addComponent(manageCategoriesButton, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addComponent(configurationButton, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addComponent(aboutButton, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addComponent(helpButton, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        tabItemsPanelLayout.setVerticalGroup(
            tabItemsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(tabItemsPanelLayout.createSequentialGroup()
                .addComponent(overviewButton, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(accountsButton, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(accountActivitiesButton, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(expensesButton, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(earningsButton, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(budgetButton, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(manageCategoriesButton, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(reportsButton, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(configurationButton, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(aboutButton, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(helpButton, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 251, Short.MAX_VALUE))
        );

        jLayeredPane1.setPreferredSize(new java.awt.Dimension(868, 669));

        overviewPanel.setPreferredSize(new java.awt.Dimension(858, 669));
        overviewPanel.setLayout(null);

        defaultAccLabel.setFont(new java.awt.Font("Segoe UI Semilight", 0, 18)); // NOI18N
        defaultAccLabel.setText("Cash");
        overviewPanel.add(defaultAccLabel);
        defaultAccLabel.setBounds(20, 40, 140, 25);

        defaultAccBalanceLabel.setFont(new java.awt.Font("Segoe UI Semilight", 0, 18)); // NOI18N
        defaultAccBalanceLabel.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        defaultAccBalanceLabel.setText("Rs. 100.00");
        overviewPanel.add(defaultAccBalanceLabel);
        defaultAccBalanceLabel.setBounds(150, 40, 150, 25);

        defAccIncome.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        defAccIncome.setText("Income");
        overviewPanel.add(defAccIncome);
        defAccIncome.setBounds(20, 65, 60, 20);

        defAccIncomeLabel.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        defAccIncomeLabel.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        defAccIncomeLabel.setText("Rs. 123.00");
        overviewPanel.add(defAccIncomeLabel);
        defAccIncomeLabel.setBounds(150, 65, 150, 20);

        defAccExpense.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        defAccExpense.setText("Expense");
        overviewPanel.add(defAccExpense);
        defAccExpense.setBounds(20, 85, 60, 20);

        defAccExpenseLabel.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        defAccExpenseLabel.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        defAccExpenseLabel.setText("Rs.100.00");
        overviewPanel.add(defAccExpenseLabel);
        defAccExpenseLabel.setBounds(150, 85, 150, 20);

        secondAccountLabel.setFont(new java.awt.Font("Segoe UI Semilight", 0, 18)); // NOI18N
        secondAccountLabel.setText("Second account");
        overviewPanel.add(secondAccountLabel);
        secondAccountLabel.setBounds(20, 130, 140, 25);

        secondAccountBalance.setFont(new java.awt.Font("Segoe UI Semilight", 0, 18)); // NOI18N
        secondAccountBalance.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        secondAccountBalance.setText("Rs. 100.00");
        overviewPanel.add(secondAccountBalance);
        secondAccountBalance.setBounds(150, 130, 150, 25);

        secAccIncomeLabel.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        secAccIncomeLabel.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        secAccIncomeLabel.setText("Rs. 123.00");
        overviewPanel.add(secAccIncomeLabel);
        secAccIncomeLabel.setBounds(150, 155, 150, 20);

        secAccExpenseLabel.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        secAccExpenseLabel.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        secAccExpenseLabel.setText("Rs.100.00");
        overviewPanel.add(secAccExpenseLabel);
        secAccExpenseLabel.setBounds(150, 175, 150, 20);

        secAccExpense.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        secAccExpense.setText("Expense");
        overviewPanel.add(secAccExpense);
        secAccExpense.setBounds(20, 175, 60, 20);

        secAccIncome.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        secAccIncome.setText("Income");
        overviewPanel.add(secAccIncome);
        secAccIncome.setBounds(20, 155, 60, 20);

        accSummaryBox.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/epicsoft/expensemanager/guiImages/Accountsummaryboxbg.png"))); // NOI18N
        accSummaryBox.setPreferredSize(new java.awt.Dimension(300, 250));
        overviewPanel.add(accSummaryBox);
        accSummaryBox.setBounds(10, 10, 300, 200);

        addExpenseButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/epicsoft/expensemanager/guiImages/AddExpense.png"))); // NOI18N
        addExpenseButton.setText("jLabel1");
        addExpenseButton.setPreferredSize(new java.awt.Dimension(300, 50));
        addExpenseButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                addExpenseButtonMouseClicked(evt);
            }
        });
        overviewPanel.add(addExpenseButton);
        addExpenseButton.setBounds(10, 240, 300, 40);

        addEarningButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/epicsoft/expensemanager/guiImages/AddEarning.png"))); // NOI18N
        addEarningButton.setText("jLabel2");
        addEarningButton.setPreferredSize(new java.awt.Dimension(300, 50));
        addEarningButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                addEarningButtonMouseClicked(evt);
            }
        });
        overviewPanel.add(addEarningButton);
        addEarningButton.setBounds(10, 290, 300, 40);

        accountsPanel.setPreferredSize(new java.awt.Dimension(858, 669));

        addNewAccountButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/epicsoft/expensemanager/guiImages/AddNewActive.png"))); // NOI18N
        addNewAccountButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                addNewAccountButtonMouseClicked(evt);
            }
        });

        editAccountButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/epicsoft/expensemanager/guiImages/EditButtonInactive.png"))); // NOI18N

        deleteAccountButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/epicsoft/expensemanager/guiImages/DeleteButtonInactive.png"))); // NOI18N

        viewActivitiesButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/epicsoft/expensemanager/guiImages/Transfer.png"))); // NOI18N

        transferButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/epicsoft/expensemanager/guiImages/ViewActivitiesInactive.png"))); // NOI18N
        transferButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                transferButtonMouseClicked(evt);
            }
        });

        accountTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Name", "Account Type", "Initial Balance", "Current Balance"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.Double.class, java.lang.Double.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane2.setViewportView(accountTable);

        javax.swing.GroupLayout accountsPanelLayout = new javax.swing.GroupLayout(accountsPanel);
        accountsPanel.setLayout(accountsPanelLayout);
        accountsPanelLayout.setHorizontalGroup(
            accountsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(accountsPanelLayout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 613, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(accountsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(transferButton)
                    .addComponent(viewActivitiesButton, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(deleteAccountButton, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(editAccountButton, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(addNewAccountButton, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(53, Short.MAX_VALUE))
        );
        accountsPanelLayout.setVerticalGroup(
            accountsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(accountsPanelLayout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addGroup(accountsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                    .addGroup(accountsPanelLayout.createSequentialGroup()
                        .addComponent(viewActivitiesButton, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(transferButton)
                        .addGap(82, 82, 82)
                        .addComponent(addNewAccountButton, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(editAccountButton, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(deleteAccountButton, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(89, 89, 89))
        );

        accountActivitiesPanel.setPreferredSize(new java.awt.Dimension(858, 669));

        accountLabel.setText("Account");

        accountComboBox.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        AccActivityTimePeriod.add(allTimeRadioButton);
        allTimeRadioButton.setText("All Time");

        AccActivityTimePeriod.add(yearlyRadioButton);
        yearlyRadioButton.setText("Yearly");

        AccActivityTimePeriod.add(monthlyRadioButton);
        monthlyRadioButton.setText("Monthly");

        AccActivityTimePeriod.add(dailyRadioButton);
        dailyRadioButton.setText("Daily");

        deleteButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/epicsoft/expensemanager/guiImages/DeleteButtonInactive.png"))); // NOI18N

        editButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/epicsoft/expensemanager/guiImages/EditButtonInactive.png"))); // NOI18N

        addNewButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/epicsoft/expensemanager/guiImages/AddNewActive.png"))); // NOI18N

        javax.swing.GroupLayout accountActivitiesPanelLayout = new javax.swing.GroupLayout(accountActivitiesPanel);
        accountActivitiesPanel.setLayout(accountActivitiesPanelLayout);
        accountActivitiesPanelLayout.setHorizontalGroup(
            accountActivitiesPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(accountActivitiesPanelLayout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addComponent(accountLabel)
                .addGap(18, 18, 18)
                .addComponent(accountComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(allTimeRadioButton)
                .addGap(18, 18, 18)
                .addComponent(yearlyRadioButton)
                .addGap(18, 18, 18)
                .addComponent(monthlyRadioButton)
                .addGap(18, 18, 18)
                .addComponent(dailyRadioButton)
                .addContainerGap(419, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, accountActivitiesPanelLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(accountActivitiesPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(deleteButton, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(editButton, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(addNewButton, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(53, 53, 53))
        );
        accountActivitiesPanelLayout.setVerticalGroup(
            accountActivitiesPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(accountActivitiesPanelLayout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addGroup(accountActivitiesPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(accountLabel)
                    .addComponent(accountComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(allTimeRadioButton)
                    .addComponent(yearlyRadioButton)
                    .addComponent(monthlyRadioButton)
                    .addComponent(dailyRadioButton))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(addNewButton, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(editButton, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(deleteButton, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(478, Short.MAX_VALUE))
        );

        expensesPanel.setPreferredSize(new java.awt.Dimension(858, 669));

        expenseCategoryComboBox.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        CategoryLabel.setText("Category");

        addNewButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/epicsoft/expensemanager/guiImages/AddNewActive.png"))); // NOI18N
        addNewButton1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                addNewButton1MouseClicked(evt);
            }
        });

        editButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/epicsoft/expensemanager/guiImages/EditButtonInactive.png"))); // NOI18N

        deleteButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/epicsoft/expensemanager/guiImages/DeleteButtonInactive.png"))); // NOI18N

        EarningsTimePeriod.add(allTimeRadioButton1);
        allTimeRadioButton1.setText("All Time");

        EarningsTimePeriod.add(yearlyRadioButton1);
        yearlyRadioButton1.setText("Yearly");

        EarningsTimePeriod.add(monthlyRadioButton1);
        monthlyRadioButton1.setText("Monthly");

        EarningsTimePeriod.add(dailyRadioButton1);
        dailyRadioButton1.setText("Daily");

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null}
            },
            new String [] {
                "Account", "Date", "Category", "Amount", "Payment Method", "Description"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.Double.class, java.lang.String.class, java.lang.String.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        jScrollPane1.setViewportView(jTable1);

        javax.swing.GroupLayout expensesPanelLayout = new javax.swing.GroupLayout(expensesPanel);
        expensesPanel.setLayout(expensesPanelLayout);
        expensesPanelLayout.setHorizontalGroup(
            expensesPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(expensesPanelLayout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addGroup(expensesPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(expensesPanelLayout.createSequentialGroup()
                        .addComponent(CategoryLabel)
                        .addGap(18, 18, 18)
                        .addComponent(expenseCategoryComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(194, 194, 194)
                        .addComponent(allTimeRadioButton1)
                        .addGap(18, 18, 18)
                        .addComponent(yearlyRadioButton1)
                        .addGap(18, 18, 18)
                        .addComponent(monthlyRadioButton1)
                        .addGap(18, 18, 18)
                        .addComponent(dailyRadioButton1))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 595, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 34, Short.MAX_VALUE)
                .addGroup(expensesPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(deleteButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(editButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(addNewButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(53, 53, 53))
        );
        expensesPanelLayout.setVerticalGroup(
            expensesPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(expensesPanelLayout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addGroup(expensesPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(expensesPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(allTimeRadioButton1)
                        .addComponent(yearlyRadioButton1)
                        .addComponent(monthlyRadioButton1)
                        .addComponent(dailyRadioButton1))
                    .addGroup(expensesPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(CategoryLabel)
                        .addComponent(expenseCategoryComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(4, 4, 4)
                .addGroup(expensesPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(expensesPanelLayout.createSequentialGroup()
                        .addComponent(addNewButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(editButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(deleteButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 436, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(146, Short.MAX_VALUE))
        );

        earningsPanel.setPreferredSize(new java.awt.Dimension(858, 669));

        earningCategoryComboBox.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        accountLabel2.setText("Category");

        addNewButton2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/epicsoft/expensemanager/guiImages/AddNewActive.png"))); // NOI18N

        editButton2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/epicsoft/expensemanager/guiImages/EditButtonInactive.png"))); // NOI18N

        deleteButton2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/epicsoft/expensemanager/guiImages/DeleteButtonInactive.png"))); // NOI18N

        EarningsTimePeriod.add(yearlyRadioButton2);
        yearlyRadioButton2.setText("Yearly");

        EarningsTimePeriod.add(allTimeRadioButton2);
        allTimeRadioButton2.setText("All Time");

        EarningsTimePeriod.add(monthlyRadioButton2);
        monthlyRadioButton2.setText("Monthly");

        EarningsTimePeriod.add(dailyRadioButton2);
        dailyRadioButton2.setText("Daily");

        javax.swing.GroupLayout earningsPanelLayout = new javax.swing.GroupLayout(earningsPanel);
        earningsPanel.setLayout(earningsPanelLayout);
        earningsPanelLayout.setHorizontalGroup(
            earningsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(earningsPanelLayout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addComponent(accountLabel2)
                .addGap(18, 18, 18)
                .addComponent(earningCategoryComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(allTimeRadioButton2)
                .addGap(18, 18, 18)
                .addComponent(yearlyRadioButton2)
                .addGap(18, 18, 18)
                .addComponent(monthlyRadioButton2)
                .addGap(18, 18, 18)
                .addComponent(dailyRadioButton2)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, earningsPanelLayout.createSequentialGroup()
                .addContainerGap(655, Short.MAX_VALUE)
                .addGroup(earningsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(deleteButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(editButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(addNewButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(53, 53, 53))
        );
        earningsPanelLayout.setVerticalGroup(
            earningsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(earningsPanelLayout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addGroup(earningsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(earningsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(allTimeRadioButton2)
                        .addComponent(yearlyRadioButton2)
                        .addComponent(monthlyRadioButton2)
                        .addComponent(dailyRadioButton2))
                    .addGroup(earningsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(accountLabel2)
                        .addComponent(earningCategoryComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(addNewButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(editButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(deleteButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(478, Short.MAX_VALUE))
        );

        budgetPanel.setPreferredSize(new java.awt.Dimension(858, 669));

        javax.swing.GroupLayout budgetPanelLayout = new javax.swing.GroupLayout(budgetPanel);
        budgetPanel.setLayout(budgetPanelLayout);
        budgetPanelLayout.setHorizontalGroup(
            budgetPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 858, Short.MAX_VALUE)
        );
        budgetPanelLayout.setVerticalGroup(
            budgetPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 660, Short.MAX_VALUE)
        );

        manageCategoriesPanel.setPreferredSize(new java.awt.Dimension(858, 669));

        addCategoryButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/epicsoft/expensemanager/guiImages/AddNewActive.png"))); // NOI18N
        addCategoryButton.setText("jLabel1");
        addCategoryButton.setPreferredSize(new java.awt.Dimension(150, 40));
        addCategoryButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                addCategoryButtonMouseClicked(evt);
            }
        });

        editCateogryButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/epicsoft/expensemanager/guiImages/EditButtonInactive.png"))); // NOI18N
        editCateogryButton.setText("jLabel2");
        editCateogryButton.setPreferredSize(new java.awt.Dimension(150, 40));

        deleteCategoryButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/epicsoft/expensemanager/guiImages/DeleteButtonInactive.png"))); // NOI18N
        deleteCategoryButton.setText("jLabel3");
        deleteCategoryButton.setPreferredSize(new java.awt.Dimension(150, 40));

        javax.swing.GroupLayout manageCategoriesPanelLayout = new javax.swing.GroupLayout(manageCategoriesPanel);
        manageCategoriesPanel.setLayout(manageCategoriesPanelLayout);
        manageCategoriesPanelLayout.setHorizontalGroup(
            manageCategoriesPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, manageCategoriesPanelLayout.createSequentialGroup()
                .addContainerGap(677, Short.MAX_VALUE)
                .addGroup(manageCategoriesPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(deleteCategoryButton, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(editCateogryButton, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(addCategoryButton, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(31, 31, 31))
        );
        manageCategoriesPanelLayout.setVerticalGroup(
            manageCategoriesPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(manageCategoriesPanelLayout.createSequentialGroup()
                .addGap(53, 53, 53)
                .addComponent(addCategoryButton, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(31, 31, 31)
                .addComponent(editCateogryButton, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(43, 43, 43)
                .addComponent(deleteCategoryButton, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(422, Short.MAX_VALUE))
        );

        reportPanel.setPreferredSize(new java.awt.Dimension(858, 669));

        javax.swing.GroupLayout reportPanelLayout = new javax.swing.GroupLayout(reportPanel);
        reportPanel.setLayout(reportPanelLayout);
        reportPanelLayout.setHorizontalGroup(
            reportPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 858, Short.MAX_VALUE)
        );
        reportPanelLayout.setVerticalGroup(
            reportPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 660, Short.MAX_VALUE)
        );

        configurationPanel.setPreferredSize(new java.awt.Dimension(858, 669));

        javax.swing.GroupLayout configurationPanelLayout = new javax.swing.GroupLayout(configurationPanel);
        configurationPanel.setLayout(configurationPanelLayout);
        configurationPanelLayout.setHorizontalGroup(
            configurationPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 858, Short.MAX_VALUE)
        );
        configurationPanelLayout.setVerticalGroup(
            configurationPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 660, Short.MAX_VALUE)
        );

        aboutPanel.setPreferredSize(new java.awt.Dimension(858, 669));

        javax.swing.GroupLayout aboutPanelLayout = new javax.swing.GroupLayout(aboutPanel);
        aboutPanel.setLayout(aboutPanelLayout);
        aboutPanelLayout.setHorizontalGroup(
            aboutPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 858, Short.MAX_VALUE)
        );
        aboutPanelLayout.setVerticalGroup(
            aboutPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 680, Short.MAX_VALUE)
        );

        helpPanel.setPreferredSize(new java.awt.Dimension(858, 669));

        javax.swing.GroupLayout helpPanelLayout = new javax.swing.GroupLayout(helpPanel);
        helpPanel.setLayout(helpPanelLayout);
        helpPanelLayout.setHorizontalGroup(
            helpPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 858, Short.MAX_VALUE)
        );
        helpPanelLayout.setVerticalGroup(
            helpPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 680, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout jLayeredPane1Layout = new javax.swing.GroupLayout(jLayeredPane1);
        jLayeredPane1.setLayout(jLayeredPane1Layout);
        jLayeredPane1Layout.setHorizontalGroup(
            jLayeredPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 874, Short.MAX_VALUE)
            .addGroup(jLayeredPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(overviewPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(jLayeredPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jLayeredPane1Layout.createSequentialGroup()
                    .addComponent(accountsPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
            .addGroup(jLayeredPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jLayeredPane1Layout.createSequentialGroup()
                    .addComponent(accountActivitiesPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
            .addGroup(jLayeredPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jLayeredPane1Layout.createSequentialGroup()
                    .addComponent(expensesPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
            .addGroup(jLayeredPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jLayeredPane1Layout.createSequentialGroup()
                    .addComponent(earningsPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
            .addGroup(jLayeredPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jLayeredPane1Layout.createSequentialGroup()
                    .addComponent(budgetPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 19, Short.MAX_VALUE)))
            .addGroup(jLayeredPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jLayeredPane1Layout.createSequentialGroup()
                    .addComponent(manageCategoriesPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 19, Short.MAX_VALUE)))
            .addGroup(jLayeredPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jLayeredPane1Layout.createSequentialGroup()
                    .addComponent(reportPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 19, Short.MAX_VALUE)))
            .addGroup(jLayeredPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jLayeredPane1Layout.createSequentialGroup()
                    .addComponent(configurationPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 19, Short.MAX_VALUE)))
            .addGroup(jLayeredPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jLayeredPane1Layout.createSequentialGroup()
                    .addComponent(aboutPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 19, Short.MAX_VALUE)))
            .addGroup(jLayeredPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jLayeredPane1Layout.createSequentialGroup()
                    .addComponent(helpPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 19, Short.MAX_VALUE)))
        );
        jLayeredPane1Layout.setVerticalGroup(
            jLayeredPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
            .addGroup(jLayeredPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jLayeredPane1Layout.createSequentialGroup()
                    .addComponent(overviewPanel, javax.swing.GroupLayout.PREFERRED_SIZE, 630, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
            .addGroup(jLayeredPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(accountsPanel, javax.swing.GroupLayout.PREFERRED_SIZE, 630, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(jLayeredPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(accountActivitiesPanel, javax.swing.GroupLayout.PREFERRED_SIZE, 630, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(jLayeredPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(expensesPanel, javax.swing.GroupLayout.PREFERRED_SIZE, 630, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(jLayeredPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(earningsPanel, javax.swing.GroupLayout.PREFERRED_SIZE, 630, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(jLayeredPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jLayeredPane1Layout.createSequentialGroup()
                    .addComponent(budgetPanel, javax.swing.GroupLayout.PREFERRED_SIZE, 660, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 31, Short.MAX_VALUE)))
            .addGroup(jLayeredPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jLayeredPane1Layout.createSequentialGroup()
                    .addComponent(manageCategoriesPanel, javax.swing.GroupLayout.PREFERRED_SIZE, 660, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 31, Short.MAX_VALUE)))
            .addGroup(jLayeredPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jLayeredPane1Layout.createSequentialGroup()
                    .addComponent(reportPanel, javax.swing.GroupLayout.PREFERRED_SIZE, 660, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 31, Short.MAX_VALUE)))
            .addGroup(jLayeredPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jLayeredPane1Layout.createSequentialGroup()
                    .addComponent(configurationPanel, javax.swing.GroupLayout.PREFERRED_SIZE, 660, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 31, Short.MAX_VALUE)))
            .addGroup(jLayeredPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jLayeredPane1Layout.createSequentialGroup()
                    .addComponent(aboutPanel, javax.swing.GroupLayout.PREFERRED_SIZE, 680, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
            .addGroup(jLayeredPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jLayeredPane1Layout.createSequentialGroup()
                    .addComponent(helpPanel, javax.swing.GroupLayout.PREFERRED_SIZE, 680, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
        );
        jLayeredPane1.setLayer(overviewPanel, javax.swing.JLayeredPane.PALETTE_LAYER);
        jLayeredPane1.setLayer(accountsPanel, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane1.setLayer(accountActivitiesPanel, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane1.setLayer(expensesPanel, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane1.setLayer(earningsPanel, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane1.setLayer(budgetPanel, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane1.setLayer(manageCategoriesPanel, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane1.setLayer(reportPanel, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane1.setLayer(configurationPanel, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane1.setLayer(aboutPanel, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane1.setLayer(helpPanel, javax.swing.JLayeredPane.DEFAULT_LAYER);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(activeUserLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(changeUserButton, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(43, 43, 43))
            .addGroup(layout.createSequentialGroup()
                .addComponent(tabItemsPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(jLayeredPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 874, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(5, 5, 5)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(activeUserLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(changeUserButton, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(tabItemsPanel, javax.swing.GroupLayout.PREFERRED_SIZE, 691, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLayeredPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 630, javax.swing.GroupLayout.PREFERRED_SIZE)))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void accountsButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_accountsButtonMouseClicked
        changeInterface(1, "AccountsActive.png");
        fillAccountTable();
    }//GEN-LAST:event_accountsButtonMouseClicked

    private void overviewButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_overviewButtonMouseClicked
        changeInterface(0, "OverviewActive.png");
    }//GEN-LAST:event_overviewButtonMouseClicked

    private void accountActivitiesButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_accountActivitiesButtonMouseClicked
        changeInterface(2, "AccountActivitiesActive.png");
    }//GEN-LAST:event_accountActivitiesButtonMouseClicked

    private void expensesButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_expensesButtonMouseClicked
        changeInterface(3, "ExpensesActive.png");
    }//GEN-LAST:event_expensesButtonMouseClicked

    private void earningsButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_earningsButtonMouseClicked
        changeInterface(4, "EarningsActive.png");
    }//GEN-LAST:event_earningsButtonMouseClicked

    private void budgetButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_budgetButtonMouseClicked
        changeInterface(5, "BudgetActive.png");
    }//GEN-LAST:event_budgetButtonMouseClicked

    private void manageCategoriesButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_manageCategoriesButtonMouseClicked
        changeInterface(6, "ManageCategoriesActive.png");
    }//GEN-LAST:event_manageCategoriesButtonMouseClicked

    private void reportsButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_reportsButtonMouseClicked
        changeInterface(7, "ReportsActive.png");
    }//GEN-LAST:event_reportsButtonMouseClicked

    private void configurationButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_configurationButtonMouseClicked
        changeInterface(8, "ConfigurationActive.png");
    }//GEN-LAST:event_configurationButtonMouseClicked

    private void aboutButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_aboutButtonMouseClicked
        changeInterface(9, "AboutActive.png");
    }//GEN-LAST:event_aboutButtonMouseClicked

    private void helpButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_helpButtonMouseClicked
        changeInterface(10, "HelpActive.png");
    }//GEN-LAST:event_helpButtonMouseClicked

    private void transferButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_transferButtonMouseClicked
        accountActivitiesButtonMouseClicked(evt);
    }//GEN-LAST:event_transferButtonMouseClicked

    private void addExpenseButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_addExpenseButtonMouseClicked
        AddExpenseDialogbox addExpense = new AddExpenseDialogbox(activeUser, this, rootPaneCheckingEnabled);
        addExpense.setVisible(true);
    }//GEN-LAST:event_addExpenseButtonMouseClicked

    private void addEarningButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_addEarningButtonMouseClicked
        AddIncomeDialogbox addIncome = new AddIncomeDialogbox(this, rootPaneCheckingEnabled, getActiveUser());
        addIncome.setVisible(true);
    }//GEN-LAST:event_addEarningButtonMouseClicked

    private void changeUserButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_changeUserButtonMouseClicked
        LoginFrame lf = new LoginFrame();
        this.dispose();
        lf.setVisible(true);
    }//GEN-LAST:event_changeUserButtonMouseClicked

    private void addCategoryButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_addCategoryButtonMouseClicked
        AddCategoryDialogBox addCategory = new AddCategoryDialogBox();
        addCategory.setVisible(true);
    }//GEN-LAST:event_addCategoryButtonMouseClicked

    private void addNewButton1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_addNewButton1MouseClicked
        AddExpenseDialogbox addExpense = new AddExpenseDialogbox(activeUser, this, rootPaneCheckingEnabled);
        addExpense.setVisible(true);
    }//GEN-LAST:event_addNewButton1MouseClicked

    private void addNewAccountButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_addNewAccountButtonMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_addNewAccountButtonMouseClicked

    private void fillAccountTable() {
        AccountController accController = new AccountController();
        
        try {
            List<Account> accountList = accController.getAllAccounts();
            
            for (Account acc: accountList) {
                Object[] row = {acc.getAccountName(), acc.getAccountType(), acc.getInitialBalance(), acc.getCurrentBalance()};
                accountDTM.addRow(row);
            }
            
        } catch (ClassNotFoundException ex) {
            Logger.getLogger(MainWindow.class.getName()).log(Level.SEVERE, null, ex);
        } catch (SQLException ex) {
            Logger.getLogger(MainWindow.class.getName()).log(Level.SEVERE, null, ex);
        }
    }
    
    public void setActiveUser(String user){
        activeUser = user;
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MainWindow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MainWindow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MainWindow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MainWindow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        
        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            @Override
            public void run() {
                new MainWindow().setVisible(true);
            }
        });
    }
    
    @Override
    public void setVisible(boolean b){
        super.setVisible(b);
        this.overviewButtonMouseClicked(null);
        activeUserLabel.setText(getActiveUser());
    }
    /**
     * Change the button images and set visible the selected panel.
     * @param btnNo
     * @param img 
     */
    private void changeInterface(int btnNo, String img) {
        for (int i = 0; i < panelList.length  ; i++) {
            if (btnNo == i) {
                panelList[i].setVisible(true);
                continue;
            }
            
            panelList[i].setVisible(false);
        }
        
        buttonList[0].setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/epicsoft/expensemanager/guiImages/OverViewInactive.png")));
        buttonList[1].setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/epicsoft/expensemanager/guiImages/AccountsInactive.png")));
        buttonList[2].setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/epicsoft/expensemanager/guiImages/AccountActivitiesInactive.png")));
        buttonList[3].setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/epicsoft/expensemanager/guiImages/ExpensesInactive.png")));
        buttonList[4].setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/epicsoft/expensemanager/guiImages/EarningsInactive.png")));
        buttonList[5].setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/epicsoft/expensemanager/guiImages/BudgetInactive.png")));
        buttonList[6].setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/epicsoft/expensemanager/guiImages/ManageCategoriesInactive.png")));
        buttonList[7].setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/epicsoft/expensemanager/guiImages/ReportsInactive.png")));
        buttonList[8].setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/epicsoft/expensemanager/guiImages/ConfigurationInactive.png")));
        buttonList[9].setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/epicsoft/expensemanager/guiImages/AboutInactive.png")));
        buttonList[10].setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/epicsoft/expensemanager/guiImages/HelpInactive.png")));
        
        buttonList[btnNo].setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/epicsoft/expensemanager/guiImages/"+img)));
        
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup AccActivityTimePeriod;
    private javax.swing.JLabel CategoryLabel;
    private javax.swing.ButtonGroup EarningsTimePeriod;
    private javax.swing.ButtonGroup ExpenseTimePeriod;
    private javax.swing.JLabel aboutButton;
    private javax.swing.JPanel aboutPanel;
    private javax.swing.JLabel accSummaryBox;
    private javax.swing.JLabel accountActivitiesButton;
    private javax.swing.JPanel accountActivitiesPanel;
    private javax.swing.JComboBox accountComboBox;
    private javax.swing.JLabel accountLabel;
    private javax.swing.JLabel accountLabel2;
    private javax.swing.JTable accountTable;
    private javax.swing.JLabel accountsButton;
    private javax.swing.JPanel accountsPanel;
    private javax.swing.JLabel activeUserLabel;
    private javax.swing.JLabel addCategoryButton;
    private javax.swing.JLabel addEarningButton;
    private javax.swing.JLabel addExpenseButton;
    private javax.swing.JLabel addNewAccountButton;
    private javax.swing.JLabel addNewButton;
    private javax.swing.JLabel addNewButton1;
    private javax.swing.JLabel addNewButton2;
    private javax.swing.JRadioButton allTimeRadioButton;
    private javax.swing.JRadioButton allTimeRadioButton1;
    private javax.swing.JRadioButton allTimeRadioButton2;
    private javax.swing.JLabel budgetButton;
    private javax.swing.JPanel budgetPanel;
    private javax.swing.JLabel changeUserButton;
    private javax.swing.JLabel configurationButton;
    private javax.swing.JPanel configurationPanel;
    private javax.swing.JRadioButton dailyRadioButton;
    private javax.swing.JRadioButton dailyRadioButton1;
    private javax.swing.JRadioButton dailyRadioButton2;
    private javax.swing.JLabel defAccExpense;
    private javax.swing.JLabel defAccExpenseLabel;
    private javax.swing.JLabel defAccIncome;
    private javax.swing.JLabel defAccIncomeLabel;
    private javax.swing.JLabel defaultAccBalanceLabel;
    private javax.swing.JLabel defaultAccLabel;
    private javax.swing.JLabel deleteAccountButton;
    private javax.swing.JLabel deleteButton;
    private javax.swing.JLabel deleteButton1;
    private javax.swing.JLabel deleteButton2;
    private javax.swing.JLabel deleteCategoryButton;
    private javax.swing.JComboBox earningCategoryComboBox;
    private javax.swing.JLabel earningsButton;
    private javax.swing.JPanel earningsPanel;
    private javax.swing.JLabel editAccountButton;
    private javax.swing.JLabel editButton;
    private javax.swing.JLabel editButton1;
    private javax.swing.JLabel editButton2;
    private javax.swing.JLabel editCateogryButton;
    private javax.swing.JComboBox expenseCategoryComboBox;
    private javax.swing.JLabel expensesButton;
    private javax.swing.JPanel expensesPanel;
    private javax.swing.JLabel helpButton;
    private javax.swing.JPanel helpPanel;
    private javax.swing.JLayeredPane jLayeredPane1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable jTable1;
    private javax.swing.JLabel manageCategoriesButton;
    private javax.swing.JPanel manageCategoriesPanel;
    private javax.swing.JRadioButton monthlyRadioButton;
    private javax.swing.JRadioButton monthlyRadioButton1;
    private javax.swing.JRadioButton monthlyRadioButton2;
    private javax.swing.JLabel overviewButton;
    private javax.swing.JPanel overviewPanel;
    private javax.swing.JPanel reportPanel;
    private javax.swing.JLabel reportsButton;
    private javax.swing.JLabel secAccExpense;
    private javax.swing.JLabel secAccExpenseLabel;
    private javax.swing.JLabel secAccIncome;
    private javax.swing.JLabel secAccIncomeLabel;
    private javax.swing.JLabel secondAccountBalance;
    private javax.swing.JLabel secondAccountLabel;
    private javax.swing.JPanel tabItemsPanel;
    private javax.swing.JLabel transferButton;
    private javax.swing.JLabel viewActivitiesButton;
    private javax.swing.JRadioButton yearlyRadioButton;
    private javax.swing.JRadioButton yearlyRadioButton1;
    private javax.swing.JRadioButton yearlyRadioButton2;
    // End of variables declaration//GEN-END:variables

    /**
     * @return the activeUser
     */
    public String getActiveUser() {
        return activeUser;
    }
}
